### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by ArturoAngonJose** [SistemasTecTlaxiaco/infografia-de-las-librerias-ArturoAngonJose#2]
[INFOGRAFIA.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-las-librerias-ArturoAngonJose/files/6308141/INFOGRAFIA.pdf)

**Comment by Eva155** [comment]
Faltó incluir imágenes
Calificación: 18 puntos
Calificó: Eva Aguilar Avendaño

**Comment by josealfredo79** [comment]
Bien hecho y revisado
